/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClaimVehicleRouteImport } from './routes/_authenticated/claim-vehicle'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardMechanicalRouteImport } from './routes/_authenticated/dashboard/mechanical'
import { Route as AuthenticatedDashboardEngineRouteImport } from './routes/_authenticated/dashboard/engine'
import { Route as AuthenticatedDashboardElectricalRouteImport } from './routes/_authenticated/dashboard/electrical'
import { Route as AuthenticatedDashboardDigitalTwinRouteImport } from './routes/_authenticated/dashboard/digital-twin'
import { Route as AuthenticatedDashboardBrakesRouteImport } from './routes/_authenticated/dashboard/brakes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClaimVehicleRoute =
  AuthenticatedClaimVehicleRouteImport.update({
    id: '/claim-vehicle',
    path: '/claim-vehicle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMechanicalRoute =
  AuthenticatedDashboardMechanicalRouteImport.update({
    id: '/mechanical',
    path: '/mechanical',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEngineRoute =
  AuthenticatedDashboardEngineRouteImport.update({
    id: '/engine',
    path: '/engine',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardElectricalRoute =
  AuthenticatedDashboardElectricalRouteImport.update({
    id: '/electrical',
    path: '/electrical',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDigitalTwinRoute =
  AuthenticatedDashboardDigitalTwinRouteImport.update({
    id: '/digital-twin',
    path: '/digital-twin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBrakesRoute =
  AuthenticatedDashboardBrakesRouteImport.update({
    id: '/brakes',
    path: '/brakes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/claim-vehicle': typeof AuthenticatedClaimVehicleRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/brakes': typeof AuthenticatedDashboardBrakesRoute
  '/dashboard/digital-twin': typeof AuthenticatedDashboardDigitalTwinRoute
  '/dashboard/electrical': typeof AuthenticatedDashboardElectricalRoute
  '/dashboard/engine': typeof AuthenticatedDashboardEngineRoute
  '/dashboard/mechanical': typeof AuthenticatedDashboardMechanicalRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/claim-vehicle': typeof AuthenticatedClaimVehicleRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard/brakes': typeof AuthenticatedDashboardBrakesRoute
  '/dashboard/digital-twin': typeof AuthenticatedDashboardDigitalTwinRoute
  '/dashboard/electrical': typeof AuthenticatedDashboardElectricalRoute
  '/dashboard/engine': typeof AuthenticatedDashboardEngineRoute
  '/dashboard/mechanical': typeof AuthenticatedDashboardMechanicalRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/claim-vehicle': typeof AuthenticatedClaimVehicleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard/brakes': typeof AuthenticatedDashboardBrakesRoute
  '/_authenticated/dashboard/digital-twin': typeof AuthenticatedDashboardDigitalTwinRoute
  '/_authenticated/dashboard/electrical': typeof AuthenticatedDashboardElectricalRoute
  '/_authenticated/dashboard/engine': typeof AuthenticatedDashboardEngineRoute
  '/_authenticated/dashboard/mechanical': typeof AuthenticatedDashboardMechanicalRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/claim-vehicle'
    | '/dashboard'
    | '/dashboard/brakes'
    | '/dashboard/digital-twin'
    | '/dashboard/electrical'
    | '/dashboard/engine'
    | '/dashboard/mechanical'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/signup'
    | '/claim-vehicle'
    | '/'
    | '/dashboard/brakes'
    | '/dashboard/digital-twin'
    | '/dashboard/electrical'
    | '/dashboard/engine'
    | '/dashboard/mechanical'
    | '/dashboard'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/signup'
    | '/_authenticated/claim-vehicle'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/dashboard/brakes'
    | '/_authenticated/dashboard/digital-twin'
    | '/_authenticated/dashboard/electrical'
    | '/_authenticated/dashboard/engine'
    | '/_authenticated/dashboard/mechanical'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/claim-vehicle': {
      id: '/_authenticated/claim-vehicle'
      path: '/claim-vehicle'
      fullPath: '/claim-vehicle'
      preLoaderRoute: typeof AuthenticatedClaimVehicleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mechanical': {
      id: '/_authenticated/dashboard/mechanical'
      path: '/mechanical'
      fullPath: '/dashboard/mechanical'
      preLoaderRoute: typeof AuthenticatedDashboardMechanicalRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/engine': {
      id: '/_authenticated/dashboard/engine'
      path: '/engine'
      fullPath: '/dashboard/engine'
      preLoaderRoute: typeof AuthenticatedDashboardEngineRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/electrical': {
      id: '/_authenticated/dashboard/electrical'
      path: '/electrical'
      fullPath: '/dashboard/electrical'
      preLoaderRoute: typeof AuthenticatedDashboardElectricalRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/digital-twin': {
      id: '/_authenticated/dashboard/digital-twin'
      path: '/digital-twin'
      fullPath: '/dashboard/digital-twin'
      preLoaderRoute: typeof AuthenticatedDashboardDigitalTwinRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/brakes': {
      id: '/_authenticated/dashboard/brakes'
      path: '/brakes'
      fullPath: '/dashboard/brakes'
      preLoaderRoute: typeof AuthenticatedDashboardBrakesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBrakesRoute: typeof AuthenticatedDashboardBrakesRoute
  AuthenticatedDashboardDigitalTwinRoute: typeof AuthenticatedDashboardDigitalTwinRoute
  AuthenticatedDashboardElectricalRoute: typeof AuthenticatedDashboardElectricalRoute
  AuthenticatedDashboardEngineRoute: typeof AuthenticatedDashboardEngineRoute
  AuthenticatedDashboardMechanicalRoute: typeof AuthenticatedDashboardMechanicalRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBrakesRoute: AuthenticatedDashboardBrakesRoute,
    AuthenticatedDashboardDigitalTwinRoute:
      AuthenticatedDashboardDigitalTwinRoute,
    AuthenticatedDashboardElectricalRoute:
      AuthenticatedDashboardElectricalRoute,
    AuthenticatedDashboardEngineRoute: AuthenticatedDashboardEngineRoute,
    AuthenticatedDashboardMechanicalRoute:
      AuthenticatedDashboardMechanicalRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClaimVehicleRoute: typeof AuthenticatedClaimVehicleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClaimVehicleRoute: AuthenticatedClaimVehicleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
